name: Superinteligencias
favicon: null
layout_spectrum: 0.50041
typography_spectrum: 0.5651225098408759
title: De la inteligencia natural a la sintética y vuelta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9daebe'
    - '#040404'
    - '#ffffff'
    - '#3f4c5f'
    - '#d1d6db'
  brandStrength: 0.08734599128365517
  lightness: 0.9192766265477985
  saturation: 0.38545189425349236
  rhythmicContrast: 0.6822328655980527
purpose: []
